General:
 model: 		# (str) subcutaneous or intravenous
 compartments:          # (int) number of peripheral compartments
 rate:		    	# (float) the absorption rate constant (ka)

Protocol:
 dosing:	        # (float) total dosage administered
 times:			# (list) of administration times comma delimited
 scale:			# (0) specify the exponent to scale dosage by over time

Output:
 visualise: 		# (bool) whether to visualise the output as a plot
 verbose:		# (bool) whether to stream outputs in verbose mode