General:
 model: intravenous 	# (str) subcutaneous or intravenous
 compartments: 2        # (int) number of peripheral compartments
 rate: 1		# (float)(/h) the absorption rate constant (ka)
 doseX:	1		# (float)(mg) the dose quantity administered (X)

Protocol:
 times: 1000	        # (list or int) of administration times comma delimited
 scale:	0		# (int: 0 or 1) specify the exponent to scale dosage by over time

Output:
 visualise: True 	# (bool) whether to visualise the output as a plot
 verbose: False		# (bool) whether to stream outputs in verbose mode

Parameters:
 V_c: 1.0			# (float)(mL) volume of central compartment
 V_p1: 1.0			# (float)(mL) volume of peripheral compartment 1
 CL: 1.0			# (float)(mL/h) clearance/elimination rate from central compartment
 Q_p1: 1.0			# (float)(mL/h) transition rate between central and peripheral 1
 
 